name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Set up PocketBase binary
      - name: Ensure PocketBase is executable
        run: |
          chmod +x ./pocketbase

      # Run the PocketBase server
      - name: Start PocketBase
        run: |
          ./pocketbase serve
