name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Ensure PocketBase binary is executable
      - name: Ensure PocketBase is executable
        run: chmod +x ./pocketbase

      # Start PocketBase server
      - name: Start PocketBase server
        run: |
          ./pocketbase serve --http 0.0.0.0:8080 &
          
      # Wait for server to initialize
      - name: Wait for server to be ready
        run: sleep 5

      # Deploy frontend/public assets using GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
